name: Learn Go
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25127
title: Learn How To Play Go - Understanding The Rules Of Go
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eadeea'
    - '#0e032d'
    - '#312435'
    - '#b19ea0'
    - '#8f3f36'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
